
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author juan
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }
double algebra[]= new double[1555];
double algoritmia[]= new double[1555];
double Introduccion[]= new double[1555];
double Catedra[]= new double[1555];
double crecimiento[]= new double[1555];
double competencia[]= new double[1555];

String nombres[]= new String[1555];
double codigo[]= new double[1555];
static int cont;



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jtxt_nom = new javax.swing.JTextField();
        jtx_cod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxt_Sem = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jtxt_asig = new javax.swing.JComboBox<>();
        jtxt_n3 = new javax.swing.JTextField();
        jtxt_n1 = new javax.swing.JTextField();
        jtxt_n2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        label1.setText("label1");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/USB.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jtxt_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_nomActionPerformed(evt);
            }
        });
        getContentPane().add(jtxt_nom);
        jtxt_nom.setBounds(120, 40, 200, 30);
        getContentPane().add(jtx_cod);
        jtx_cod.setBounds(120, 90, 200, 30);

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 50, 110, 20);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 370, 90, 30);

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 370, 80, 30);

        jLabel3.setText("Semestre");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 160, 110, 30);

        jLabel4.setText("Nota 1");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 300, 70, 30);

        jLabel5.setText("Nota 2");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 300, 90, 30);

        jLabel6.setText("Nota 3");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(270, 300, 110, 30);

        jLabel7.setText("Código");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 100, 110, 20);

        jtxt_Sem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        jtxt_Sem.setSelectedItem(1);
        jtxt_Sem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_SemFocusGained(evt);
            }
        });
        getContentPane().add(jtxt_Sem);
        jtxt_Sem.setBounds(120, 160, 200, 30);

        jLabel8.setText("Asignatura");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 220, 110, 30);

        jtxt_asig.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_asigFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxt_asigFocusLost(evt);
            }
        });
        jtxt_asig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_asigActionPerformed(evt);
            }
        });
        getContentPane().add(jtxt_asig);
        jtxt_asig.setBounds(120, 220, 200, 30);
        getContentPane().add(jtxt_n3);
        jtxt_n3.setBounds(260, 330, 90, 20);
        getContentPane().add(jtxt_n1);
        jtxt_n1.setBounds(20, 330, 90, 20);

        jtxt_n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_n2ActionPerformed(evt);
            }
        });
        getContentPane().add(jtxt_n2);
        jtxt_n2.setBounds(140, 330, 90, 20);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/ct_universidad_simon_bolivar.jpg"))); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jLabel9.setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, -50, 400, 510);

        setBounds(0, 0, 402, 431);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_nomActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int cod= Integer.parseInt(jtx_cod.getText());
        int pos=-1;
        if(cod==0){
            JOptionPane.showMessageDialog(null, "Por favor llene el campo");
        }else{
            for(int i=0; i<codigo.length; i++){
                if(codigo[i]==cod){
                    pos=0;
                
                }
            }
            if(pos==-1){
                nombres[cont]= jtxt_nom.getText();
                codigo[cont]= cod;
                
                String ais= jtxt_asig.getSelectedItem()+"";
                double promedio=0;
                switch(ais){
                    
                    case "Algoritmia":
                        
                       promedio= Double.parseDouble(jtxt_n1.getText())*0.3 
                              +Double.parseDouble(jtxt_n2.getText())*0.3 
                               + Double.parseDouble(jtxt_n3.getText())*0.4;
                        algoritmia[cont]=promedio;
                        break;
                        
                    case "Algebra":
                        promedio= Double.parseDouble(jtxt_n1.getText())*0.3 
                              +Double.parseDouble(jtxt_n2.getText())*0.3 
                               + Double.parseDouble(jtxt_n3.getText())*0.4;
                        algebra[cont]=promedio;
                        
                        
                        break;
                        
                        
                }
                
                
                JOptionPane.showMessageDialog(this, "Guardado con éxito");
                cont=cont+1;
                jtx_cod.setText("");
                jtxt_nom.setText("");
                
                
                
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int cod= Integer.parseInt(jtx_cod.getText());
        int pos=-1;
        int in=0;
        if(cod==0){
            JOptionPane.showMessageDialog(null, "Por favor llene el campo");
        }else{
            for(int i=0; i<codigo.length; i++){
                if(codigo[i]==cod){
                    pos=0;
                    in=i;
                
                }
                
            }
            if(pos==0){
                    jtxt_nom.setText(nombres[in]);
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Estudiante no registrado");
                    jtx_cod.setText("");
                    jtxt_nom.setText("");
                }
            
            
        }
            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtxt_asigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_asigActionPerformed
       
       
    }//GEN-LAST:event_jtxt_asigActionPerformed

    private void jtxt_asigFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_asigFocusGained
       String semestre=jtxt_Sem.getSelectedItem()+"";
       switch(semestre){
           case "1":
               jtxt_asig.removeAllItems();
               jtxt_asig.addItem("Algebra");
               jtxt_asig.addItem("Algoritmia");
               
               
               break;
           case "2":
               jtxt_asig.removeAllItems();
               jtxt_asig.addItem("Calculo Diferencial");
               break;
       }        
    }//GEN-LAST:event_jtxt_asigFocusGained

    private void jtxt_SemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_SemFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_SemFocusGained

    private void jtxt_asigFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_asigFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_asigFocusLost

    private void jtxt_n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_n2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_n2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jtx_cod;
    private javax.swing.JComboBox<String> jtxt_Sem;
    private javax.swing.JComboBox<String> jtxt_asig;
    private javax.swing.JTextField jtxt_n1;
    private javax.swing.JTextField jtxt_n2;
    private javax.swing.JTextField jtxt_n3;
    private javax.swing.JTextField jtxt_nom;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
